//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TractionTools.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIResult() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TractionTools.Tests.Properties.APIResult", typeof(APIResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;DetailsUrl&quot;:&quot;https://notes.traction.tools/p/b1863074-0df6-43d4-a5e5-ca7bfecc45b0?showControls=true&amp;showChat=false&quot;,&quot;Owner&quot;:{&quot;Name&quot;:&quot;E1 150424568&quot;,&quot;ImageUrl&quot;:&quot;/i/userplaceholder&quot;,&quot;Initials&quot;:&quot;E 1&quot;,&quot;Managing&quot;:null,&quot;CreateTime&quot;:&quot;2017-09-01T06:01:24&quot;,&quot;Id&quot;:9,&quot;Type&quot;:&quot;AngularUser&quot;,&quot;Key&quot;:&quot;AngularUser_9&quot;,&quot;CreateOnly&quot;:false,&quot;Hide&quot;:false,&quot;_ExtraProperties&quot;:null},&quot;Name&quot;:&quot;Issue for Test Method&quot;,&quot;Details&quot;:null,&quot;Children&quot;:[],&quot;CompleteTime&quot;:null,&quot;CreateTime&quot;:&quot;2017-09-01T06:01:25&quot;,&quot;Complete&quot;:false,&quot;Priority&quot;:0,&quot;Id&quot;:1,&quot;Typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IssueApiTests_v0_TestGetMineIssues {
            get {
                return ResourceManager.GetString("IssueApiTests_v0_TestGetMineIssues", resourceCulture);
            }
        }
    }
}
