//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TractionTools.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SurveyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SurveyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TractionTools.Tests.Properties.SurveyResources", typeof(SurveyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[[{&quot;Id&quot;:0,&quot;Help&quot;:null,&quot;Name&quot;:&quot;ItemResponse: \n\tItem: User2 - Rock1 \n\tResponse: (null) \n\tFormat: [0](Radio,  {\&quot;options\&quot;:{\&quot;Done\&quot;:\&quot;done\&quot;,\&quot;Not Done\&quot;:\&quot;not-done\&quot;}}  )&quot;,&quot;Ordering&quot;:0},{&quot;Id&quot;:0,&quot;Help&quot;:null,&quot;Name&quot;:&quot;ItemResponse: \n\tItem: User2 - Rock2 \n\tResponse: (null) \n\tFormat: [0](Radio,  {\&quot;options\&quot;:{\&quot;Done\&quot;:\&quot;done\&quot;,\&quot;Not Done\&quot;:\&quot;not-done\&quot;}}  )&quot;,&quot;Ordering&quot;:0},{&quot;Id&quot;:0,&quot;Help&quot;:null,&quot;Name&quot;:&quot;ItemResponse: \n\tItem: User2 - Rock3 \n\tResponse: (null) \n\tFormat: [0](Radio,  {\&quot;options\&quot;:{\&quot;Done [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RockSectionSmokeTest {
            get {
                return ResourceManager.GetString("RockSectionSmokeTest", resourceCulture);
            }
        }
    }
}
