//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadialReview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadialReview.Properties.ConstantStrings", typeof(ConstantStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://s3.amazonaws.com/Radial/.
        /// </summary>
        public static string AmazonS3Location {
            get {
                return ResourceManager.GetString("AmazonS3Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placeholder/orgPlaceholder.png.
        /// </summary>
        public static string ImageOrganizationPlaceholder {
            get {
                return ResourceManager.GetString("ImageOrganizationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placeholder/orgPlaceholder.png.
        /// </summary>
        public static string ImagePlaceholder {
            get {
                return ResourceManager.GetString("ImagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to placeholder/placeholder.png.
        /// </summary>
        public static string ImageUserPlaceholder {
            get {
                return ResourceManager.GetString("ImageUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pop.gmail.com.
        /// </summary>
        public static string PopHost {
            get {
                return ResourceManager.GetString("PopHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton@radialreview.com.
        /// </summary>
        public static string PopLogin {
            get {
                return ResourceManager.GetString("PopLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Ztdgavv49.
        /// </summary>
        public static string PopPassword {
            get {
                return ResourceManager.GetString("PopPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 995.
        /// </summary>
        public static string PopPort {
            get {
                return ResourceManager.GetString("PopPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton@radialreview.com.
        /// </summary>
        public static string SmtpFromAddress {
            get {
                return ResourceManager.GetString("SmtpFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string SmtpHost {
            get {
                return ResourceManager.GetString("SmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton@radialreview.com.
        /// </summary>
        public static string SmtpLogin {
            get {
                return ResourceManager.GetString("SmtpLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Ztdgavv49.
        /// </summary>
        public static string SmtpPassword {
            get {
                return ResourceManager.GetString("SmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
    }
}
