//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadialReview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadialReview.Properties.EmailTypes", typeof(EmailTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyTodo.
        /// </summary>
        public static string DailyTodo {
            get {
                return ResourceManager.GetString("DailyTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinOrganization.
        /// </summary>
        public static string JoinOrganization {
            get {
                return ResourceManager.GetString("JoinOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L10Summary.
        /// </summary>
        public static string L10Summary {
            get {
                return ResourceManager.GetString("L10Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPrereviewIssued.
        /// </summary>
        public static string NewPrereviewIssued {
            get {
                return ResourceManager.GetString("NewPrereviewIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewReviewIssued.
        /// </summary>
        public static string NewReviewIssued {
            get {
                return ResourceManager.GetString("NewReviewIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentException.
        /// </summary>
        public static string PaymentException {
            get {
                return ResourceManager.GetString("PaymentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewReminder.
        /// </summary>
        public static string ReviewReminder {
            get {
                return ResourceManager.GetString("ReviewReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurveyIssued.
        /// </summary>
        public static string SurveyIssued {
            get {
                return ResourceManager.GetString("SurveyIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
