//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadialReview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadialReview.Properties.ProductStrings", typeof(ProductStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1201 Infinity Ct, Lincoln, NE 68512.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://review.radialreview.com/.
        /// </summary>
        public static string BaseUrl2 {
            get {
                return ResourceManager.GetString("BaseUrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traction Tools.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Inc..
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton@mytractiontools.com.
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://radialreview.com/.
        /// </summary>
        public static string MarketingUrl {
            get {
                return ResourceManager.GetString("MarketingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton@mytractiontools.com.
        /// </summary>
        public static string PaymentExceptionEmail {
            get {
                return ResourceManager.GetString("PaymentExceptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment-receipts@mytractiontools.com.
        /// </summary>
        public static string PaymentReceiptEmail {
            get {
                return ResourceManager.GetString("PaymentReceiptEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traction Tools.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton@radialreview.com.
        /// </summary>
        public static string PurchaseEmail {
            get {
                return ResourceManager.GetString("PurchaseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-402-437-0099.
        /// </summary>
        public static string PurchaseNumber {
            get {
                return ResourceManager.GetString("PurchaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@radialreview.com.
        /// </summary>
        public static string SupportEmail {
            get {
                return ResourceManager.GetString("SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clay.upton+test@radialreview.com.
        /// </summary>
        public static string TestEmail {
            get {
                return ResourceManager.GetString("TestEmail", resourceCulture);
            }
        }
    }
}
