//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadialReview.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadialReview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIGZTCCBU2gAwIBAgIIFtzL5iDSegIwDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNV
        ///BAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js
        ///ZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3
        ///aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw
        ///HhcNMTcxMjA0MDIxMTA4WhcNMTkwMTAzMDIxMTA4WjCBrTExMC8GCgmSJomT8ixk
        ///AQEMIW9yZy5UcmFjdGlvblRvb2xzLlRyYWN0aW9uVG9vbHNWMTE/MD0GA1UEAww2
        ///QXBwbGUgUHVzaCBTZXJ2aWNlczogb3JnLlRyYWN0aW9uVG9vbHMuVHJhY3Rpb25U
        ///b29sc1YxMRMwEQYDVQQLD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppleAPS {
            get {
                return ResourceManager.GetString("AppleAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] APS {
            get {
                object obj = ResourceManager.GetObject("APS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Checked {
            get {
                object obj = ResourceManager.GetObject("Checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap closed {
            get {
                object obj = ResourceManager.GetObject("closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .swagger-section {
        ///  background-color: #eee;
        ///  font-family: &apos;Lato&apos;, sans-serif;
        ///  /*.signature-nav {
        ///		display: none !important;
        ///	}*/
        ///}
        ///.swagger-section pre {
        ///  background-color: #efefef !important;
        ///  border: 1px solid #e4e4e4 !important;
        ///  resize: vertical;
        ///  max-height: 300px !important;
        ///  min-height: 80px;
        ///}
        ///.swagger-section #header,
        ///.swagger-section .footer {
        ///  display: none;
        ///}
        ///.swagger-section .swagger-ui-wrap {
        ///  line-height: 1;
        ///  font-family: &apos;Lato&apos;, sans-serif;
        ///  min-width: 100%;
        ///  max-width: 100%;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomSwaggerStyle {
            get {
                return ResourceManager.GetString("CustomSwaggerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EOS_Model {
            get {
                object obj = ResourceManager.GetObject("EOS_Model", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaron,erin,ronnie,ron
        ///abbie,abigail
        ///abby,abigail
        ///abe,abraham,abram
        ///abednego,bedney
        ///abel,ebbie,ab,abe,eb
        ///abiel,ab
        ///abigail,nabby,abby,gail
        ///abijah,ab,bige
        ///abner,ab
        ///abraham,ab,abe
        ///abram,ab
        ///absalom,app,ab,abbie
        ///ada,addy
        ///adaline,delia,lena,dell,addy,ada
        ///adam,edie,ade
        ///addy,adele
        ///adela,della
        ///adelaide,heidi,adele,dell,addy,della
        ///adelbert,del,albert,delbert,bert
        ///adele,dell
        ///adeline,delia,lena,dell,addy,ada
        ///adelphia,philly,delphia,adele,dell,addy
        ///adolphus,dolph,ado,adolph
        ///adrian,rian
        ///adrienne,a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Unchecked {
            get {
                object obj = ResourceManager.GetObject("Unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
